version: '2'
services:
  notebook:
    image: mesh_tools:v1
    build: 
      context: .
    env_file: .env
    environment:
      - DISPLAY=$DISPLAY
      - XSOCK=/tmp/.X11-unix/X0
    ports:
      - "8890:8888"
        #volumes:
      #- ./notebooks:/notebooks
      #- ../meshAfterParty:/meshAfterParty
      #- ../examples:/examples
      #- /mnt:/mnt

